name: Chromatic

on:
  workflow_dispatch:
    inputs:
      number:
        description: "Pull Request Number"
        required: true
    branch:
      description: "Branch Name"
      required: true

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.inputs.number }}/head"
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ">=14.16.0 14"
      - run: npm ci
      - run: npx chromatic@latest --project-token ${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-once-uploaded --branch-name="${{ github.event.inputs.branch }}"
