name: Chromatic

on:
  workflow_dispatch:
    inputs:
      number:
        description: "Pull Request Number"
        required: true

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.inputs.number }}/head"
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: ">=14.16.0 14"
      - run: npm ci
      - uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true # We don't want it to fail CI, we'll be using the GitHub Check
