name: Cypress PR

on: pull_request

jobs:
  trigger-cypress:
    # if not a fork
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: dispatch_cypress
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          workflow_id: "cypress.yml"
          ref: "main"
          inputs: '{"number": "${{ github.event.pull_request.number }}"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo PR number: ${{ github.event.pull_request.number }}"

      - name: Test curl
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/actions/workflows/cypress.yml/dispatches \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header "Accept: application/vnd.github.v3+json" \
          --data '{"ref": "main", "inputs": {"number": "7"}}'
          
