name: Cypress

on:
  workflow_dispatch:
    inputs:
      number:
        description: "Pull Request Number"
        required: true
jobs:
  cypress:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container: cypress/browsers:node14.17.0-chrome91-ff89
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "refs/pull/${{ github.event.inputs.number }}/head"
          fetch-depth: 0

      - name: Cache central NPM modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-

      - name: install dependencies and verify Cypress
        env:
          # make sure every Cypress install prints minimal information
          CI: 1
        run: |
          npm ci
          npx cypress cache path
          npx cypress cache list
          npx cypress verify
          npx cypress info

      - name: Cypress run
        uses: cypress-io/github-action@v2.10.2
        with:
          install: false
          browser: chrome
          record: true
          group: ubuntu-regression
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CI: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
