name: Cypress PR

on: pull_request

jobs:
  trigger-cypress:
    # if not a fork
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: dispatch_cypress
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          workflow_id: 'cypress.yml'
          ref: 'refs/pull/${{ github.event.inputs.number }}/head'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
