name: Manually triggered workflow escape
on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Input'
        required: true
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.escape.conclusion }}
    steps:
      - id: escape
        name: Check for escape chars
        if: ${!contains(github.event.inputs.test, '"')}
        run: success()
  chromatic:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.status == 'success'
    steps:  
      - run: echo --branch-name="${{ github.event.inputs.test }}"