name: Manually triggered workflow escape
on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Input'
        required: true
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.escape.conclusion }}
    steps:
      - id: escape
        name: Check for escape chars
        run: |
          if [ ${{ contains(github.event.inputs.test, '"') }} ]
          then
              echo "::set-output name=escape::fail"
          else
              echo "::set-output name=escape::pass"
          fi
  chromatic:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.escape == 'pass'
    steps:  
      - run: echo ${{ github.event.inputs.test }}"