name: Escape Test
on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Pull Request Number'
        required: true
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ fromJson(steps.get_pull.outputs.data).head.label }}
    steps:
      - id: get_pull
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.inputs.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: escape
        name: Check for escape chars
        run: |
          echo ${{ fromJson(steps.get_pull.outputs.data).head.label }}
          if ${{ contains(fromJson(steps.get_pull.outputs.data).head.label, '"') }}
          then
            exit 1
          else
              exit 0
          fi
      - id: debug
        run: echo ${{ fromJson(steps.get_pull.outputs.data).head.label }}
        
  chromatic:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ needs.check.output.branch_name }}"