name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      test:
        description: 'Input'
        required: true
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.escape.conclusion }}
    steps:
    - id: escape
      name: Check for escape chars
      run: |
        if ${{ contains(github.event.inputs.test, '"') }}
        then
          exit 1
        else
            exit 0
        fi
  chromatic:
    needs: check
    runs-on: ubuntu-latest
    steps:  
      - run: echo --branch-name="${{ github.event.inputs.test }}"