name: Forked CI
on:
  workflow_dispatch:
    inputs:
      number:
        description: "Pull Request Number"
        required: true

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ fromJson(steps.get_pull.outputs.data).head.label }}
    steps:
      - id: get_pull
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.inputs.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: escape
        name: Check for escape chars
        run: |
          if ${{ contains(fromJson(steps.get_pull.outputs.data).head.label, '"') }}
          then
            exit 1
          else
              exit 0
          fi

  trigger-cypress:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: dispatch_cypress
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          workflow_id: "cypress.yml"
          ref: "main"
          inputs: '{"number": "${{ github.event.inputs.number }}", "branch": "${{ needs.check.outputs.branch_name }}"}'
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}

  trigger-chromatic:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: dispatch_chromatic
        with:
          route: POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}
          workflow_id: "chromatic.yml"
          ref: "main"
          inputs: '{"number": "${{ github.event.inputs.number }}", "branch": "${{ needs.check.outputs.branch_name }}"}'
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}

    # runs-on: ubuntu-latest
    # steps:
    #   - uses: actions/checkout@v2
    #     with:
    #       ref: "refs/pull/${{ github.event.inputs.number }}/head"
    #       fetch-depth: 0
    #   - uses: actions/setup-node@v1
    #     with:
    #       node-version: ">=14.16.0 14"
    #   - run: npm ci
    #   - run: npx chromatic@latest --project-token ${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-once-uploaded --branch-name="${{ needs.check.outputs.branch_name }}"
